<?xml version="1.0" encoding="UTF-8"?>

<!-- Documento scritto da Ancora Giovanni, 5^Ci, il 28/01/2025 -->

<!DOCTYPE catalogoFilm [
    <!ELEMENT catalogoFilm (film+)>
    <!ELEMENT film (id, titolo, anno, genere, regista, cast, durata?)>
    <!ELEMENT id (#PCDATA)>
    <!ELEMENT titolo (#PCDATA)>
    <!ELEMENT anno (#PCDATA)>
    <!ELEMENT genere (#PCDATA)>
    <!ELEMENT regista (#PCDATA)>
    <!ELEMENT cast (attore+)>
    <!ELEMENT attore (nome, cognome)>
    <!ELEMENT nome (#PCDATA)>
    <!ELEMENT cognome (#PCDATA)>
    <!ELEMENT durata (#PCDATA)>
]>
<catalogoFilm>
    <film>
        <id>001</id>
        <titolo>La fabbrica di cioccolato</titolo>
        <anno>2005</anno>
        <genere>Fantastico</genere>
        <regista>Tim Burton</regista>
        <cast>
            <attore>
                <nome>Johnny</nome>
                <cognome>Depp</cognome>
            </attore>
            <attore>
                <nome>Helena</nome>
                <cognome>Bonham Carter</cognome>
            </attore>
        </cast>
        <durata>115</durata>
    </film>

    <film>
        <id>002</id>
        <titolo>Harry Potter e i Doni della morte - Parte 2</titolo>
        <anno>2011</anno>
        <genere>Fantastico</genere>
        <regista>David Yates</regista>
        <cast>
            <attore>
                <nome>Daniel</nome>
                <cognome>Radcliffe</cognome>
            </attore>
            <attore>
                <nome>Rupert</nome>
                <cognome>Grint</cognome>
            </attore>
            <attore>
                <nome>Emma</nome>
                <cognome>Watson</cognome>
            </attore>
            <attore>
                <nome>Alan</nome>
                <cognome>Rickman</cognome>
            </attore>
        </cast>
        <durata>130</durata>
    </film>

    <film>
        <id>003</id>
        <titolo>Guardiani della Galassia Vol. 3</titolo>
        <anno>2023</anno>
        <genere>Azione</genere>
        <regista>James Gunn</regista>
        <cast>
            <attore>
                <nome>Chris</nome>
                <cognome>Pratt</cognome>
            </attore>
            <attore>
                <nome>Dave</nome>
                <cognome>Bautista</cognome>
            </attore>
        </cast>
        <durata>150</durata>
    </film>
</catalogoFilm>